### ISSUE TITLE
Individual/general scheduling is broken for new applets created by the builder

### ISSUE THREAD

**Issue by Matchdev120** [ChildMindInstitute/mindlogger-admin#340]
A new applet created by the builder is scheduled  The individual scheduling is broken#221
Steps to reproduce:
1. Log in to the admin panel https://admin-staging.mindlogger.org/ (e.g. norman@ml.com // 123456)
2. Set up individual/general scheduling
3. Pay attention to the result on the device

Actual result: The individual/general scheduling is broken. The events from individual/general scheduling for the new applet are displayed on calendar but not applied on the app.
Expected result: The events for individual/general scheduling for new applets created by the builder should work.
Environment:
https://admin-staging.mindlogger.org/
MindLogger Admin v 0.3.4

**Comment by sergeysemenuta** [comment]
The issue is reproduced again
Individual/general scheduling is broken  for new applets created by the builder or duplicated applets
https://www.screencast.com/t/9qawnRGm
Test account: snakessqa@gmail.com // 123456
MindLogger app v 0.14.1
Samsung Galaxy S10 // Android 9
iPhone X // iOS 13.3
Pixel 4 XL // Android 11

**Comment by Matchdev120** [comment]
@sergeysemenuta I followed your video and tested `simple applet` in your account but it works fine as you can see.
Please check this again and let me know the steps if it is still working on your side.

![Screen Shot 2020-10-28 at 10.04.54 PM.png](https://images.zenhubusercontent.com/5e248d759c666007f1a71211/3beea33a-fd95-4a35-896e-cb710cd7762d)

**Comment by sergeysemenuta** [comment]
@Matchdev120 
Still reproduces on my side.
All activities are in unscheduled status for applets created via applet builder and duplicated applets.
It is reproduced on all my accounts
Video: https://www.screencast.com/t/EaJiuiaLc
MindLogger app v 0.14.1
Samsung Galaxy S10 // Android 9
iPhone X // iOS 13.3
Pixel 4 XL // Android 11

**Comment by sergeysemenuta** [comment]
I'm still able to reproduce the issue
All events are unscheduled for newly created  via builder/duplicated and edited applets
https://www.screencast.com/t/pqdoRxS4KGlM
MindLogger app v 0.14.4
Samsung Galaxy S10 // Android 9
iPhone X // iOS 13.3
Pixel 4 XL // Android 11

**Comment by sergeysemenuta** [comment]
The issue is fixed.
https://www.screencast.com/t/XvjgbyRbov97
Checked on:
Staging
MindLogger app v 0.14.5
Samsung Galaxy S10 // Android 9
iPhone X // iOS 13.3
Pixel 4 XL // Android 11
iPhone 8 // iOS 14.0
